# script to correlation ALT status to clinical variables

suppressPackageStartupMessages({
  library(tidyverse)
})

# output directory
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")

# read ALT status generated by Mateusz
alt_status <- read_tsv(file.path(data_dir, "hope_cohort_alt_status.txt"))

# read MSI results                       